# Generated by Django 6.1 on 2026-08-14 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(help_text='UTC, inclusive.')),
                ('end_time', models.DateTimeField(help_text='UTC, exclusive.')),
                ('horizon_candles', models.PositiveSmallIntegerField(default=10, help_text='Candles forward from a trigger used to score its forward return (ADR 0010).', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('error', models.TextField(blank=True)),
                ('trigger_count', models.PositiveIntegerField(blank=True, null=True)),
                ('scored_trigger_count', models.PositiveIntegerField(blank=True, help_text='Triggers with enough forward candles to score; <= trigger_count. The gap is triggers too close to end_time to measure a full horizon.', null=True)),
                ('win_count', models.PositiveIntegerField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_forward_return', models.FloatField(blank=True, help_text='Sum of forward returns (%) over every scored trigger — the R/R proxy; see ADR 0010.', null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategy.strategy')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
