# Generated by Django 6.1 on 2026-08-14 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(help_text='Exchange symbol, e.g. "BTCUSDT".', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='Display name, e.g. "Bitcoin / USDT".', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the ingest task fans out to this symbol.')),
            ],
            options={
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1m', '1 minute'), ('5m', '5 minutes'), ('15m', '15 minutes'), ('30m', '30 minutes'), ('1h', '1 hour'), ('4h', '4 hours'), ('1d', '1 day'), ('1w', '1 week')], max_length=3)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candles', to='market.currency')),
            ],
            options={
                'ordering': ('currency', 'interval', 'open_time'),
                'constraints': [models.UniqueConstraint(fields=('currency', 'interval', 'open_time'), name='unique_candle_per_currency_interval_open_time')],
            },
        ),
    ]
