# Generated by Django 6.1 on 2026-08-14 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(choices=[('1m', '1 minute'), ('5m', '5 minutes'), ('15m', '15 minutes'), ('30m', '30 minutes'), ('1h', '1 hour'), ('4h', '4 hours'), ('1d', '1 day'), ('1w', '1 week')], max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='market.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StrategyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_open_time', models.DateTimeField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('triggered', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='strategy.strategy')),
            ],
            options={
                'ordering': ('-evaluated_at',),
                'constraints': [models.UniqueConstraint(fields=('strategy', 'candle_open_time'), name='unique_strategy_evaluation_per_candle')],
            },
        ),
    ]
